CREATE TABLE `backchannel_requests` (
	`id` text PRIMARY KEY NOT NULL,
	`client_id` text,
	`agent_id` text,
	`agent_display_name` text NOT NULL,
	`agent_tier` text NOT NULL,
	`agent_verified` integer NOT NULL,
	`agent_directory_url` text,
	`login_hint` text NOT NULL,
	`customer_id` integer,
	`scope` text NOT NULL,
	`binding_message` text NOT NULL,
	`authorization_details` text,
	`step_up_for_order_id` integer,
	`status` text NOT NULL,
	`poll_interval_seconds` integer NOT NULL,
	`created_at` integer NOT NULL,
	`expires_at` integer NOT NULL,
	`last_polled_at` integer,
	`decided_at` integer,
	FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE no action
);
